### PR TITLE
refactor: enable geo-replication for acr images

### LINKED ISSUE #34: refactor: enable geo replication for acr images (SNYK-CC-AZURE-595)
**Message:**  Geo replication for Azure Container Images disabled ([SNYK-CC-AZURE-595](https://snyk.io/security-rules/SNYK-CC-AZURE-595))
**Severity:** `Low`

Detailed paths

    Introduced through: resource › azurerm_container_registry[this] › georeplications

This issue is...
- Geo replication for Azure Container Images disabled

The impact of this is...
- Missing geo replication leads to reduced availability of container images

You can resolve it by...
- Set a georeplications block within the resource, including a valid location property

#### References
- [Microsoft.ContainerRegistry registries/replications](https://learn.microsoft.com/en-us/azure/templates/microsoft.containerregistry/registries/replications?tabs=json&pivots=deployment-language-terraform)
- [Azure Container Registry makes geo-replication generally available, adding lifecycle management capabilities](https://azure.microsoft.com/en-gb/blog/azure-container-registry-makes-geo-replication-generally-available-adding-lifecycle-management-capabilities/)
- [Geo-replication in Azure Container Registry](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/container-registry/container-registry-geo-replication.md)

### PR DESCRIPTION
**Pull request by helenakallekleiv**
Closes #34

### CODE REVIEW

**Comment by helenakallekleiv** [comment]
Tests pass for all examples ⭐

**Review by sebastianlolv — APPROVED** [review]
Looks good 👍

**Comment by helenakallekleiv** [comment]
Test pass for complete example 👍🏼

**Review by hknutsen — CHANGES_REQUESTED** [review]
Looks to me like there is support for multiple georeplications blocks 👀

**Review by hknutsen — APPROVED** [review]
Looks good 👍

**Pull request merged**
